import Head from "next/head";
import {
  AiFillTwitterCircle,
  AiFillLinkedin,
  AiFillYoutube,
} from "react-icons/ai";
import { BsFillMoonStarsFill } from "react-icons/bs";
import { useState } from "react";
import deved from "../public/dev-ed-wave.png";
import code from "../public/code.png";
import design from "../public/design.png";
import consulting from "../public/consulting.png";
import Image from "next/image";
import web1 from "../public/web1.png";
import web2 from "../public/web2.png";
import web3 from "../public/web3.png";
import web4 from "../public/web4.png";
import web5 from "../public/web5.png";
import web6 from "../public/web6.png";

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);
  
  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Britte Alexis Portafolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='bg-white px-10 md:px-20 lg:px-40 dark:bg-gray-900'>
        <section className=' min-h-screen'>
          <nav className='py-10 mb-12 flex justify-between dark:text-white'>
            <h1 className='text-xl font-burtons'>developedbyale</h1>
            <ul className='flex items-center'>
              <li>
                <BsFillMoonStarsFill
                onClick={() => setDarkMode(!darkMode)} 
                className='cursor-pointer text-2xl'/>
              </li>
              <li>
                <a className='bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8' href='#'>Resume</a>
              </li>
            </ul>
          </nav>
          <div className='text-center p-10'>
            <h2 className='text-5xl py-2 text-teal-600 font-medium md:text-6xl dark:text-teal-400'>Britte Alexis </h2>
            <h3 className='text-2xl py-2 md:text-3xl dark:text-white'>Developer Full Stack</h3>
            <p className='text-md py-5 leading-8 text-gray-800 md:text-xl max-w-xl mx-auto dark:text-gray-200'>
              Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. 
            </p>
            <div className='text-5xl flex justify-center gap-16 py-3 text-gray-600 dark:text-gray-400'>
              <AiFillTwitterCircle />
              <AiFillLinkedin />
              <AiFillYoutube />
            </div>
            <div className='relative mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 mt-20 overflow-hidden md:h-96 md:w-96'>
              <Image src={deved} layout='fill' objectFit='cover' alt='10'/>
            </div>
          </div>
        </section>
        <section>
          <div className="text-center">
            <h3 className='text-3xl py-1 dark:text-white'>Services I offer</h3>
            <p className='text-md py-2 leading-8 text-gray-800 dark:text-gray-200'>
              Lorem Ipsum is simply dummy text of the printing and typesetting industry.
              <span className='text-teal-500 '>
              Lorem </span>Ipsum is simply dummy text of the printing and <span className='text-teal-500'>typesetting industry.
            </span>
            </p>
            <p className='text-md py-2 leading-8 text-gray-800 dark:text-gray-200'>
              Lorem Ipsum is simply dummy text of the printing and typesetting industry.
            </p>
          </div>
          <div className="lg:flex gap-10">
            <div className='text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white flex-1'>
              <Image src={design} width={100} height={100} alt='1'/>
              <h3 className='text-lg font-medium pt-8 pb-2'>Beatiful Designs</h3>
              <p className='py-2'>
                Lorem Ipsum is simply dummy text of the printing and typesetting industry.
              </p>
              <h4 className='py-4 text-teal-600'>Design tools I use</h4>
              <p className='text-gray-800 py-1'>Illustrator</p>
              <p className='text-gray-800 py-1'>Photoshop</p>
              <p className='text-gray-800 py-1'>Figma</p>
            </div>
            <div className='text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white flex-1'>
              <Image src={consulting} width={100} height={100} alt='2'/>
              <h3 className='text-lg font-medium pt-8 pb-2'>Beatiful Designs</h3>
              <p className='py-2'>
                Lorem Ipsum is simply dummy text of the printing and typesetting industry.
              </p>
              <h4 className='py-4 text-teal-600'>Design tools I use</h4>
              <p className='text-gray-800 py-1'>Illustrator</p>
              <p className='text-gray-800 py-1'>Photoshop</p>
              <p className='text-gray-800 py-1'>Figma</p>
            </div>
            <div className='text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white flex-1'>
              <Image src={code} width={100} height={100} alt='9'/>
              <h3 className='text-lg font-medium pt-8 pb-2'>Beatiful Designs</h3>
              <p className='py-2'>
                Lorem Ipsum is simply dummy text of the printing and typesetting industry.
              </p>
              <h4 className='py-4 text-teal-600'>Design tools I use</h4>
              <p className='text-gray-800 py-1'>Illustrator</p>
              <p className='text-gray-800 py-1'>Photoshop</p>
              <p className='text-gray-800 py-1'>Figma</p>
            </div>
          </div>
        </section>
        <section>
          <div className="text-center">
            <h3 className='text-3xl py-1 dark:text-white'>Portafolio</h3>
            <p className='text-md py-2 leading-8 text-gray-800 dark:text-gray-200'>
              Lorem Ipsum is simply dummy text of the printing and typesetting industry.
              <span className='text-teal-500'>
              Lorem </span>Ipsum is simply dummy text of the printing and <span className='text-teal-500'>typesetting industry.
            </span>
            </p>
            <p className='text-md py-2 leading-8 text-gray-800 dark:text-gray-200'>
              Lorem Ipsum is simply dummy text of the printing and typesetting industry.
            </p>
          </div>
          <div className="flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap">
            <div className="basis-1/3 flex-1">
              <div className="rounded-lg object-cover" width={'100%'} height={'100%'} layout='responsive'><Image src={web1} alt='3'/></div>
            </div>
            <div className="basis-1/3 flex-1">
              <div className="rounded-lg object-cover" width={'100%'} height={'100%'} layout='responsive'><Image src={web2} alt='4'/></div>
            </div>
            <div className="basis-1/3 flex-1">
              <div className="rounded-lg object-cover" width={'100%'} height={'100%'} layout='responsive'><Image src={web3} alt='5'/></div>
            </div>
            <div className="basis-1/3 flex-1">
              <div className="rounded-lg object-cover" width={'100%'} height={'100%'} layout='responsive'><Image src={web4} alt='6'/></div>
            </div>
            <div className="basis-1/3 flex-1">
              <div className="rounded-lg object-cover" width={'100%'} height={'100%'} layout='responsive'><Image src={web5} alt='67'/></div>
            </div>
            <div className="basis-1/3 flex-1">
              <div className="rounded-lg object-cover" width={'100%'} height={'100%'} layout='responsive'><Image src={web6} alt='8'/></div>
            </div>
          </div>
        </section>
      </main>
    </div>
  )
}
